name: Deploy
on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "deno install"

      - name: Run Migrations
        env: 
          PG_USER: ${{ secrets.PG_USER }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_HOSTNAME: ${{ secrets.PG_HOSTNAME }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USE_TLS: ${{ secrets.PG_USE_TLS }}
        run: "deno -A --node-modules-dir npm:drizzle-kit migrate"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "prt-tracker-zing"
          entrypoint: "src/main.ts"
          root: ""
          import-map: deno.json
